apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-gateway
  labels:
    tags.datadoghq.com/env: demo
    tags.datadoghq.com/service: api-gateway
    tags.datadoghq.com/version: "0.1.0"
spec:
  replicas: 2
  selector: { matchLabels: { app: api-gateway } }
  template:
    metadata:
      labels: 
        app: api-gateway
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/api-gateway.checks: |
          {
            "krakend": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:9090/metrics",
                  "process_metrics": true,
                  "go_metrics": true
                }
              ]
            }
          }
        admission.datadoghq.com/go-lib.version: latest
    spec:
      containers:
      - name: api-gateway
        image: 659775407889.dkr.ecr.ap-northeast-2.amazonaws.com/api-gateway:latest
        ports:
        - containerPort: 8080
        - containerPort: 9090
        env:
        - {name: DD_LOGS_INJECTION, value: "true"}
        - {name: DD_APPSEC_ENABLED, value: "true"}
        - {name: DD_TRACE_ENABLED, value: "true"}
        readinessProbe: { httpGet: { path: "/health", port: 8080 }, initialDelaySeconds: 5 }
        livenessProbe: { httpGet: { path: "/health", port: 8080 }, initialDelaySeconds: 10 }
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata: { name: api-gateway-svc }
spec:
  selector: { app: api-gateway }
  ports: 
  - { port: 8080, targetPort: 8080, name: api }
  - { port: 9090, targetPort: 9090, name: metrics }
