apiVersion: v1
kind: Pod
metadata:
  name: nat-test-pod
  namespace: fargate
  labels:
    fargate: "true"
spec:
  containers:
  - name: test-container
    image: public.ecr.aws/amazonlinux/amazonlinux:2
    command: ["sh", "-c"]
    args:
    - |
      echo "Testing NAT Gateway connectivity..."
      
      # Test DNS resolution
      echo "1. Testing DNS resolution:"
      nslookup google.com
      
      # Test HTTP connectivity
      echo "2. Testing HTTP connectivity:"
      curl -I https://httpbin.org/ip
      
      # Test Docker Hub connectivity
      echo "3. Testing Docker Hub connectivity:"
      curl -I https://registry-1.docker.io/v2/
      
      # Keep the pod running
      sleep 3600
