apiVersion: v1
kind: Pod
metadata:
  name: eviction-test-memory
  labels:
    app: eviction-test
spec:
  containers:
  - name: memory-consumer
    image: polinux/stress
    command:
    - stress
    - --vm
    - "1"
    - --vm-bytes
    - "250M"
    - --vm-hang
    - "1"
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
  restartPolicy: Never

